mkgif/urls.py
from django.urls import path
from . import views


app_name = 'mkgif'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>/', views.details, name='details'),
]

mkgif_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('mkgif.urls')),
] + static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mkgif/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
import django_rq
from .utils import mk_gif_ffmpeg

class Animation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.id} - {self.name}'
    
    def enqueue(self, params):
        django_rq.enqueue(mk_gif_ffmpeg, {
            'pk': self.pk,
            'params': params,
            }
        )

class Image(models.Model):
    def __str__(self):
        return f'{self.image}'

    def image_path(self, filename):
        return f'{self.animation.pk}/{filename}'

    animation = models.ForeignKey('Animation', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path)
    
    

mkgif/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Animation, Image


@login_required
def index(request):
    print('*'*30)
    print(request.user)

    if request.method == 'POST':
        anim = Animation.objects.create(user=request.user, name=request.POST['name'])
        
        for img in request.FILES.getlist('imgs'):
            Image.objects.create(animation=anim, image=img)

    anims = Animation.objects.filter(user=request.user)
    context = {
            'anims': anims
            }
    return render(request, 'mkgif/index.html', context)

@login_required
def details(request, pk):
    anim = get_object_or_404(Animation, pk=pk)
    images = Image.objects.filter(animation=pk)
    context = {
            'anim': anim,
            'images': images
            }
    return render(request, 'mkgif/details.html', context)

mkgif/templates/mkgif/details.html
<!-- mkgif/templates/mkgif/details.html -->

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Make GIF</title>
      {% load static %}
   </head>
   <body>
      <header>
	 <h1>Details</h1>
      </header>
      <main>
	 {{anim.name}} <br>
	 {% for img in images %}
	    <img src="{{ img.image.url }}" >
	 {% endfor %}
      </main>
   </body>
</html>

mkgif/templates/mkgif/index.html
<!-- mkgif/templates/mkgif/index.html -->

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
      <title>Make GIF</title>
   </head>
   <body>
      <header>
	 <h1>Make GIF Animations</h1>
      </header>
      <nav>
	 <ul>
	    <li><a href="{% url 'mkgif:index' %}">Home</a></li>
	    <li>
	       <span>{{ user }}</span>
	       <ul>
		  {% if user.is_superuser %}
		  <li><a href="{% url 'admin:index' %}">Django Admin</a></li>
		  {% endif %}
		  <li><a href="{% url 'logout' %}">Logout</a></li>
	       </ul>
	       </span>
	    </li>
	 </ul>
      </nav>
      <main>
	 <p>My GIF Animations:</p>
	 <table>
	    {% for anim in anims %}
	    <tr>
	       <td>{{ anim.pk }}</td>
	       <td><a href="{% url 'mkgif:details' anim.pk %}">{{ anim.name }}</a></td>
	    </tr>
	    {% endfor %}
	 </table>
	 <hr>
	 <form action="{% url 'mkgif:index' %}" method="POST" enctype="multipart/form-data">
	    <fieldset>
	       <legend><label>Add New GIF Animation</label></legend>
	       {% csrf_token %}
	       <input name="name" type="text" placeholder="Animation name">
	       <input name="imgs" type="file" multiple>
	       <button>Submit</button>
	    </fieldset>
	 </form>
      </main>
   </body>
</html>